<html>
<head><title>blogs</title>
</head>
<body background="back-green.png">
<?php
$blogtype1=$_GET['HIDDEN1'];
$blogtype2=$_GET['HIDDEN2'];
$blogtype3=$_GET['HIDDEN3'];
$blogtype4=$_GET['HIDDEN4'];
$NAME=$_GET['BLOGFIELD'];
echo ("BLOG TYPES<br>");
echo "<br>";
echo "<a href='logout.php'>LOG OUT</a>";
echo "<a href='#Heading 1'>$blogtype1</a><br>";
echo "<br>";

echo "<a href='#Heading 2'>$blogtype2</a><br>";
echo "<br>";
echo "<a href='#Heading 3'>$blogtype3</a><br>";
echo "<br>";
echo "<a href='#Heading 4'>$blogtype4</a><br>";
echo "<br>";
echo "<br><br><br><br><br>";
echo "<a name='Heading 1'>$blogtype1</a><br>";
echo "Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.   capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.
      Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.
      A capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.";
echo "<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>";	  

echo "<a name='Heading 2'>$blogtype2</a><br>";

echo "Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.   capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.
      Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.
      A capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.";
echo "<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>";

echo "<a name='Heading 3'>$blogtype3</a><br>";
echo "Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.   capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.
      Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.
      A capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.";
echo "<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>";

echo "<a name='Heading 4'>$blogtype4</a><br>";
echo "Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.   capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.
      Reactive power flow on the alternating current transmission system is needed to support the transfer of real power over the network. In alternating current circuits energy is stored temporarily in inductive and capacitive elements, which can result in the periodic reversal of the direction of energy flow. The portion of power flow remaining after being averaged over a complete AC waveform is the real power, which is energy that can be used to do work (for example overcome friction in a motor, or heat an element). On the other hand the portion of power flow that is temporarily stored in the form of electric or magnetic fields, due to inductive and capacitive network elements, and returned to source is known as the reactive power.
      AC connected devices that store energy in the form of a magnetic field include inductive devices called reactors, which consist of a large coil of wire. When a voltage is initially placed across the coil a magnetic field builds up, and it takes a period of time for the current to reach full value. This causes the current to lag the voltage in phase, and hence these devices are said to absorb reactive power.
      A capacitor is an AC device that stores energy in the form of an electric field. When current is driven through the capacitor, it takes a period of time for charge to build up to produce the full voltage difference. On an AC network the voltage across a capacitor is always changing – the capacitor will oppose this change causing the voltage to lag behind the current. In other words the current leads the voltage in phase, and hence these devices are said to generate reactive power.
      Energy stored in capacitive or inductive elements of the network give rise to reactive power flow. Reactive power flow strongly influences the voltage levels across the network. Voltage levels and reactive power flow must be carefully controlled to allow a power system to be operated within acceptable limits.";
echo "<br><br><br><br>";
echo "<a href='sample.php'>CLICK here to go back</a>";
?>
</body>
</html>

